### ISSUE TITLE
Fix Sepolia v2

### ISSUE THREAD

**Issue by franzns** [balancer/backend#1073]
Seems to be mainly caused by blocks subgraph

**Comment by mendesfabio** [comment]
this is syncing https://api.studio.thegraph.com/query/48427/bleu-sepolia-blocks/version/latest/graphql?query=%7B%0A%09_meta+%7B%0A++++block+%7B%0A++++++number%0A++++%7D%0A++%7D%0A%7D%0A

**Comment by franzns** [comment]
added it to the config in the api
