### ISSUE TITLE
How to sync holders count

### ISSUE THREAD

**Issue by franzns** [balancer/backend#1082]
HoldersCount cant be queried via rpc query but must come from subgraph. Its the only dynamic field we sync from there. It seems overkill to query each pool on the subgraph when we sync pools just to get the holders count as well. 

In the old sync model, holders count was synced along with life time stats such as `swapsCount` or `lifetimeVolume`, I think we should sync holders count also in this context as HoldersCount doesnt seem like a very important field that needs to be updated in real time.

**Comment by gmbronco** [comment]
holdersCount can be coming from the user balances which we already have in the DB. Balance syncing just needs to be made reliable https://github.com/balancer/backend/issues/1083
