### ISSUE TITLE
User Balance syncing issues

### ISSUE THREAD

**Issue by gmbronco** [balancer/backend#1083]
User BPT balances aren't properly synced with the subgraph. Current syncing relies on subgraph to have the balances at the moment of storing the pool data in the database. Turns out that's not working well. What could be other strategies for syncing?

* Since API is just syncing it's DB with the subgraph's DB, a simple row count check would hint if they are out of sync.
* When checking ERC20 transfer events we can add a safety margin to the block range and fetch X earlier blocks.
* We can use HoldersCount to check when user balances are out of sync for a specific pool

**Comment by franzns** [comment]
Lets try to add a safety margin of 200 blocks

**Comment by gmbronco** [comment]
The issue was solved by #1104
