### ISSUE TITLE
add owners for v3 pools

### ISSUE THREAD

**Issue by franzns** [balancer/backend#1086]
v3 pools have different ownership concept, need to integrate this:

On a pool, natively there can be a:
- SwapFeeManager - Can set swap fee
- PauseManager - Can pause the pool
- PoolCreator - Can set fee splits

**Comment by franzns** [comment]
How about amp?

**Comment by franzns** [comment]
```if SwapFeeManager or PauseManager are not set, the fallback is that the authorizer controls permissions. The StablePool delegates permissions for amp updates to the authorizer as well```

**Comment by gmbronco** [comment]
All 3 roles are set on pool creation. V2 owner is equivalent of V3 swapFeeManager.
