### ISSUE TITLE
fix getChangedPools via RPC for v3

### ISSUE THREAD

**Issue by franzns** [balancer/backend#1271]
https://github.com/balancer/backend/commit/e81774efe2fb43c8dac4a02bd1c9651d6e17068f#diff-aceb52fc7bf35003f5d1603a272ff3e2feb89c4a4c3f729b10aa4b5188740836R266 

need to find why it fails, might be change of ABIs in the prod deployment

**Comment by gmbronco** [comment]
it was missing token data updates, not related to RPC
