### ISSUE TITLE
investigate allow listing process for v3

### ISSUE THREAD

**Issue by franzns** [balancer/backend#18]
Balancer has processes for allow listing:
- tokens
- pools
- rateproviders

how do we handle those in v3? Seems in v2 they're handled via API by using the /hal endpoint and create PRs.

**Comment by Xeonus** [comment]
From a business perspective it is desired to streamline this process. So far Maxis had to:

upon pool creation:
- whitelist pool
- whitelist rate provider
- whitelist tokens
- make sure assets get priced

For gauges:
- maintain a "stakeable list" per chain: Example mainnet: https://github.com/balancer/frontend-v2/blob/develop/src/lib/config/mainnet/pools.ts  
- make sure gauge is added to gauge controller (should happen automatically)
- make sure correct gauge is set - sometimes multiple gauges have been created for the same pool -> have to set preferrential gauge
- stake small amounts and call claim for rewards to show up (should be legacy now)

Ideally, this flow gets simplified in v3

**Comment by franzns** [comment]
> From a business perspective it is desired to streamline this process. So far Maxis had to:
> 
> upon pool creation:
> 
> * whitelist pool
> * whitelist rate provider
> * whitelist tokens
> * make sure assets get priced

Hopefully no need to whitelist the pool anymore on v3. Rest still needs to be done.

> 
> For gauges:
> 
> * maintain a "stakeable list" per chain: Example mainnet: https://github.com/balancer/frontend-v2/blob/develop/src/lib/config/mainnet/pools.ts
> * make sure gauge is added to gauge controller (should happen automatically)
> * make sure correct gauge is set - sometimes multiple gauges have been created for the same pool -> have to set preferrential gauge
> * stake small amounts and call claim for rewards to show up (should be legacy now)

No need for the "stakeable list" anymore. Still need to set the preferential gauge, at least if there are multiple gauges. But might be good to do it in any case. One thing we need to add is making sure that the rewardToken is known by the API, either by creating a pool with the reward token or by adding a means to add them the API.


Meta data repo has been created that holds the Featured pools as well as the pool categories for filters: https://github.com/balancer/metadata

Tokenlists are handled here: https://github.com/balancer/tokenlists

Would be great if rateProviders would also be added to the metadata repo. Hopefully we can also integrate the tokenslists there. That means we would have a central place for all metadata.

**Comment by franzns** [comment]
ask @mendesfabio about why we need pool allow list
