### ISSUE TITLE
integrate v3 pool snapshots

### ISSUE THREAD

**Issue by franzns** [balancer/backend#185]

**Comment by franzns** [comment]
related to #105 

Waiting for @mendesfabio for missing data points (volume, holders count, swap count)

**Comment by mendesfabio** [comment]
I've shared [this](https://api.studio.thegraph.com/proxy/31386/balancer-v3-sepolia/v23/graphql?query=%7B%0A%09pools(%0A++++first:+1%0A++)+%7B%0A%09++id%0A++++symbol%0A++++swapsCount%0A++++holdersCount%0A++++tokens+%7B%0A++++++id%0A++++++symbol%0A++++++balance%0A++++++volume%0A++++%7D%0A++++snapshots+%7B%0A++++++id%0A++++++timestamp%0A++++++swapsCount%0A++++++holdersCount%0A++++++totalVolumes%0A++++%7D%0A%09%7D%0A%7D) with @gmbronco and will iterate on it with him
