### ISSUE TITLE
v3 pool field and liquidity updates updates

### ISSUE THREAD

**Issue by franzns** [balancer/backend#187]
- [x] Update existing pools with subgraph data (e.g. when new fields are available)
- [x] updateLiquidity24hAgoForAllPools
- [ ] updateLifetimeValuesForAllPools

**Comment by gmbronco** [comment]
> Update existing pools with subgraph data (e.g. when new fields are available)

Our current general approach is to always use upserts for subgraph syncing and update all the fields in one call. More pool types will add complexity, but we can handle them independently with separate pool-type specific jobs.

**Comment by gmbronco** [comment]
Moving "updateLifetimeValuesForAllPools" into separate ticket. https://github.com/balancer/backend/issues/391
