### ISSUE TITLE
Price tokens using reference prices

### ISSUE THREAD

**Issue by gmbronco** [balancer/backend#232]
Sometimes there are legit tokens without CG / swap pricing, like: DAI / USDC on zkEVM – in these cases we can set their price to a "reference" token, eg: DAI on polygon, or mainnet. This kind of solution could be implemented in a separate token pricing handler picking up unpriced tokens and matching them with reference ones. We would need to add a "reference_price" field to the tokenlist jsons.

Example pool without pricing:
https://app.balancer.fi/#/zkevm/pool/0xffb847598207ec5d3f0c8d256c061e1d664db2d3000200000000000000000061

**Comment by franzns** [comment]
Working on that with zekraken. The means is in the API already, just need to get the metadata into the tokenlist repo.
