### ISSUE TITLE
add all swaps, joins and exits to the DB for v3 and v2

### ISSUE THREAD

**Issue by franzns** [balancer/backend#240]
We will store swaps, joins and exits since inception for v2 and v3. 
We should test this by adding a sync for all v2 swaps as well.
In addition, can think about how to store it to have data such as volume per token.

**Comment by franzns** [comment]
Should (singlesided) joins and exits also count towards volume?

**Comment by gmbronco** [comment]
Current swaps in the DB are missing USD values. I'm syncing them from the subgraph, but when I checked them against Dune it turned out to be quite off. We are looking for the cause.

**Comment by gmbronco** [comment]
Queries for events table became quite slow after loading ~ 1GB of swap events. I'm looking into partitioning the table, but will need to find a way around prisma.

**Comment by gmbronco** [comment]
1st remedy is to change index sorting order to desc, because that's how we query the events. if that proves to be quick, partitioning won't be necessary

**Comment by franzns** [comment]
need to load historical swaps, join and exits to the DB for prod

**Comment by franzns** [comment]
only polygon and fantom left to load

**Comment by gmbronco** [comment]
Polygon is missing block numbers in subgraph. Fantom is missing pricing before Apr 2023. Sorting out historical pricing and storing it in the DB will allow event values to be more accurate and reliable than subgraph based.

**Comment by franzns** [comment]
tracked in #314
