### ISSUE TITLE
Change the getPool query result to PoolUnion

### ISSUE THREAD

**Issue by gmbronco** [balancer/backend#272]
Return type getPool is PoolBase, but the data is prepared as PoolUnion. Might need to check if there is 100% overlap so it doesn't break things.

It's needed to read all data we produce in the query.

**Comment by franzns** [comment]
Not sure what you mean here. The data can be read using the fragment like 
```
    ... on GqlPoolGyro {
      alpha
      beta
      type
      nestingType
      tokens {
        ... on GqlPoolToken {
          ...GqlPoolToken
        }
      }
    }
```
