### ISSUE TITLE
Some V2 pools are created without dynamic data part.

### ISSUE THREAD

**Issue by gmbronco** [balancer/backend#288]
Example: 0xe1a02bab66dd4962a55332cd902e960969e66cb40001000000000000000007ff on Fantom is missing dynamic data record causing dependent jobs to fail, eg: updating liquidity.

**Comment by franzns** [comment]
shouldnt we be able to reload that for all pools? I think we ran into this problem before and the new update process should fix it

**Comment by franzns** [comment]
Is this still relevant?
