### ISSUE TITLE
Prices older than 6 months and hourly prices are missing in the DB

### ISSUE THREAD

**Issue by gmbronco** [balancer/backend#293]
Query to check the prices:

```
SELECT timestamp, COUNT(*)
FROM "PrismaTokenPrice"
GROUP BY 1
ORDER BY 1 ASC;
```

I'm not sure why we are missing so much data. I triple checked the SQL pruning and no problem there. Prices aren't getting deleted anywhere else. Any updates could cause missing hourly pricing?

**Comment by franzns** [comment]
PROD: Daily prices I can see way more back than 6 months. But hourly prices seem to only go back 2 days
TEST: Daily prices only 6 months back. Hourly prices 2 days

**Comment by franzns** [comment]
The daily prices in the test DB I recall that I have accidentally removed them at some point, hence we only have them till Sept 30th. We still have them in the prod db all the way back, so daily prices are all good.

The big question is, why are hourly prices removed after two days. It must have been introduced after March 1st. I have a DB backup from March 1st which still has hourly prices for 100 days

**Comment by franzns** [comment]
Found it https://github.com/balancer/backend/commit/6c158f5f300bb73d891026236385d6367f7990b8

Somehow that number is not converted correctly, also doesnt work if it is a string

**Comment by franzns** [comment]
fixed also on prod https://github.com/balancer/backend/pull/300

**Comment by franzns** [comment]
might not be fixed after all

**Comment by franzns** [comment]
worked on test

**Comment by franzns** [comment]
currently I see hourly prices back to April 1st for both prod and test. Let's check tomorrow again

**Comment by franzns** [comment]
Still see hourly prices back to April 1st for both prod and test. Let's check back tomorrow

**Comment by franzns** [comment]
April 1st prices still there, fixed
