### ISSUE TITLE
poolGetPool should work with non-lowercase id input

### ISSUE THREAD

**Issue by brunoguerios** [balancer/backend#307]
As a user, I'd expect the api to work with non lowercase inputs as well

**Comment by franzns** [comment]
@gmbronco whats your take? For me, I think it's fine to require lowercase inputs :)

**Comment by brunoguerios** [comment]
No worries if it adds complexity or you guys don't see value in it. 
SDK and FE are likely the main users of the API and we're aware of this, so it should be fine.
I reported because it might be tricky to other consumers as it seems like an "invisible" requirement.
Feel free to ignore 🙃

**Comment by franzns** [comment]
in general allow any-case inputs
