### ISSUE TITLE
Investigate how to integrate hooks in the API 

### ISSUE THREAD

**Issue by franzns** [balancer/backend#317]
Hooks examples in the v3 code reveal article

also talk to john regarding aggregators

**Comment by gmbronco** [comment]
Spec how API can support hooks. Ask John about the aggregator needs

**Comment by gmbronco** [comment]
Summary:
* hooks are stored on a pool at pool registration - information is emitted in PoolRegistered event
* each hook has a list of flags suggesting what it can do, eg: enableHookAdjustedAmounts, setShouldCallComputeDynamicSwapFee
* we don't entirely know how a hook changes the amounts based on the onchain data - some offchain registry with categories, use-cases might be needed, eg: changing amounts based on user state, or random events

**Comment by franzns** [comment]
https://www.notion.so/Hooks-Aggregator-SOR-Support-c78a7d5a43184eb28acd2515460feeb5

**Comment by gmbronco** [comment]
Added hook-specific handlers to fetch data such as `addLiquidityFee`. These handlers work based on hook addresses, which we match with the hook assigned to a pool. When syncing data, only pools with the added hook receive the hook-specific data.
