### ISSUE TITLE
Add token APR

### ISSUE THREAD

**Issue by gmbronco** [balancer/backend#354]
We need to be able to show individual APRs to allow clients to interpret the data on their own. That means adding / changing the "items" array into individual APRs with labels, which will make it easy to do any logic on.

I'm thinking something to standardise the response object as well, so clients don't have to handle typed fields.

```
aprs: [{
  name: "BAL staking",
  label: gauge,
  apr: XX (number in %, eg: 0.1 = 10%)
}]
```

* we get rid of range / total and just use apr as a value
* we store each individual APR, eg: individual tokens, so we know where each APR is what, where it's coming from and it's easy for clients to interpret.
* we keep it backwards compatible, and prepare a migration, so beets don't break

**Comment by franzns** [comment]
Need a way to display `my apr` for staked and unstaked position.

**Comment by franzns** [comment]
Adding a `isStakingApr` flag to each item should do the trick

**Comment by franzns** [comment]
sorted it with Gareth, there is an easy way for him to calc with the current data.

That begin said, it would make sense to add a "tokenAprs" fields which is the total of all IB tokens APR (reth, wsteth etc) so we have nativeRewardApr, SwapFeeApr, thirdPartyRewardApr and tokensApr

**Comment by franzns** [comment]
will be part of #86
