### ISSUE TITLE
Investigate Alerting/visualization of data cross checks

### ISSUE THREAD

**Issue by franzns** [balancer/backend#406]
Slack alerts can become overwhelming, maybe we need some kind of status page or data visualization using graphs

**Comment by gmbronco** [comment]
we can store last check results and show as a simple webpage, eg:
https://data-checks-dashboard.balancer.workers.dev/

**Comment by franzns** [comment]
We could also send the data as a metric to AWS. Use the token name/address as the metric name and the drift as the metric. This would even allow us to chart the drift over time
