### ISSUE TITLE
decreasing swap amounts to (very) small numbers increases the number of hops

### ISSUE THREAD

**Issue by groninge01** [balancer/backend#485]
Also see [this msg](https://discord.com/channels/638460494168064021/1240619343306293309/1250933576137048084) from discord.

See below two examples I checked. All swaps are on gnosis chain.

When trying to swap a very small amount of GNO (see screenshots) to wstETH the route uses 3 hops while both assets are in the same pool with a lot of TVL. And when you try to swap 1 GNO it just uses that pool -> 1 hop.

Also looked at USDc ->sDAI: 100USDc is 1 hop, 1USDc is 2 hops, 0.0001USDc is 4 hops.

![image](https://github.com/balancer/backend/assets/20125808/14a02eb8-8388-457b-a7b9-8269d7089a79)
![image](https://github.com/balancer/backend/assets/20125808/565fc947-10c3-4f5e-a554-f7866f258d4c)

**Comment by brunoguerios** [comment]
I don't think this is actually an issue. It just finds lower liquidity pools that are able to route the small trade, but not the big one.

**Comment by franzns** [comment]
Will we fix this or not? Please close if not

**Comment by brunoguerios** [comment]
I'll close as I believe this is not an issue.
