### ISSUE TITLE
sfrax apr not showing

### ISSUE THREAD

**Issue by franzns** [balancer/backend#50]
sfrax apr not showing on OP https://op.beets.fi/pool/0x2feb76966459d7841fa8a7ed0aa4bf574d6111bf00020000000000000000011d

Maybe other added YB aprs are also not working?

**Comment by gmbronco** [comment]
Tracked it down to the token price being 0.

[Coingecko doesn't have it](https://api.coingecko.com/api/v3/simple/token_price/optimistic-ethereum?contract_addresses=0x2dd1b4d4548accea497050619965f91f78b3b532&vs_currencies=usd)

Main difficulty in debugging is the circular dependency in the config, but at least we've got a specific case for refactoring.

Calling:

```
const service = new YbTokensAprService(...)
service.updateAprForPools(pools);
```
results in:

```
TypeError: yb_tokens_apr_service_1.YbTokensAprService is not a constructor
    at Object.<anonymous> (/Users/jareknowotka/Developer/balancer/backend/modules/network/mainnet.ts:368:9)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
```

removing APR services from configs solves the issue. call stack:
YbTokensAprService > has a dependency somewhere which is calling something from the network config > network config depends on YbTokensAprService

**Comment by franzns** [comment]
thanks for checking! I believe they are in the process of listing on coingecko
