### ISSUE TITLE
add/remove on fantom not synced

### ISSUE THREAD

**Issue by franzns** [balancer/backend#501]
add/remove events only synced up to april 20  (getEvents)

maybe other chains affected?

**Comment by gmbronco** [comment]
Events behind:

"POLYGON"	"SWAP"	1703250733
"FANTOM"	"JOIN"	1713517876
"FANTOM"	"EXIT"	1713516648
"FANTOM"	"SWAP"	1642119192
"AVALANCHE"	"SWAP"	1713501811

**Comment by franzns** [comment]
Is that a timestamp or number of events?

**Comment by gmbronco** [comment]
timestamp

**Comment by gmbronco** [comment]
The syncing issue is caused by the missing block number in the existing data. To resolve this, I cleared the table of records where blockNumber = 0 for Fantom join/exits. All of the swap data for Fantom is missing the block number as well, to keep them i'll change syncing to be based on timestamps.
