### ISSUE TITLE
Integrate merkl

### ISSUE THREAD

**Issue by franzns** [balancer/backend#532]
As an additional way of adding incentives to a pool, we'll need to integrate merkl. 

Merkl endpoint: https://api.merkl.xyz/v3/campaigns?chainIds=42161&types=1&live=true 
look for 1_<PoolAddress> to find the campaign and APR

In addition, the UI will need to display when a pool as merkl rewards and show a link for the user to claim those rewards on merkl. Question is whether we just want to show a generic link to their claim page (https://app.merkl.xyz/user/) or let the UI query their API to find any user rewards (https://api.merkl.xyz/v3/userRewards?chainId=137&user=0x1B72Bac3772050FDCaF468CcE7e20deb3cB02d89)

merkl doc: https://docs.merkl.xyz/distribute-incentives/integration-guide

**Comment by gmbronco** [comment]
hey @Zen-Maxi – which parameter in the api response is the pool?
