### ISSUE TITLE
check if 'warnings' and/or 'upgradeableComponents' return values when not null

### ISSUE THREAD

**Issue by groninge01** [balancer/backend#546]
```
these on arb have both
"0x2d6ced12420a9af5a83765a8c48be2afcd1a8feb000000000000000000000500"
"0x4b3af34eb1135d59df8b9cdc2ff07d30d05334c400000000000000000000050d"
"0xd0ec47c54ca5e20aaae4616c25c825c7f48d40690000000000000000000004ef"
```

The arbitrum pools mentioned above should have `warnings` and/or `upgradeableComponents` under `priceRateProviderData` for the specific rate providers but the api currently returns `null` for both props.

**Comment by franzns** [comment]
https://github.com/balancer/code-review/blob/main/rate-providers/registry.json

**Comment by franzns** [comment]
![Image](https://github.com/balancer/backend/assets/93920061/024ade81-f65e-443f-a9f5-26fc5b7eb8a0)

**Comment by gmbronco** [comment]
@alter-eggo – all looks good on the API side. The GBP.e token doesn't have the "safe" argument set based on the review. Same for rETH.
