### ISSUE TITLE
Add aggregateSwapFee data to pools

### ISSUE THREAD

**Issue by johngrantuk** [balancer/backend#648]
We need the aggregateSwapFee as part of hooks logic. 
aggregateSwapFee = creator + protocol and can be different per pool
Not sure if this is currently exposed anywhere on SCs so will confirm.

**Comment by gmbronco** [comment]
@johngrantuk where the creator fee is coming from, is this part of the hooks?

**Comment by johngrantuk** [comment]
> @johngrantuk where the creator fee is coming from, is this part of the hooks?

I believe its per pool but might be worth double checking.

There's a bit of info [here](https://balancerecosystem.slack.com/archives/C04KJE1U8TU/p1721918688912009) about where to get `aggregateSwapFee`.
