### ISSUE TITLE
Add ezETH APR to API

### ISSUE THREAD

**Issue by Zen-Maxi** [balancer/backend#67]
Endpoint: https://app.renzoprotocol.com/api/apr 

pool: https://app.balancer.fi/#/ethereum/pool/0x596192bb6e41802428ac943d2f1476c1af25cc0e000000000000000000000659 

token: https://etherscan.io/address/0xbf5495efe5db9ce00f80364c8b423567e58d2110

**Comment by franzns** [comment]
@Zen-Maxi will give it a shot to create a PR for it
