### ISSUE TITLE
null value for nullable field

### ISSUE THREAD

**Issue by franzns** [balancer/backend#68]
sentry error: https://skloon.sentry.io/issues/4748062784/?environment=multichain-canary&environment=multichain-main&project=4504774210158592&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=90d&stream_index=0

![Image](https://github.com/balancer/backend/assets/93920061/948750c3-286e-4c01-bce0-ba30d3fb4d35)

**Comment by franzns** [comment]
User balancer should always be linked to a pool ID, why is it even null? probably related to this change https://github.com/balancer/backend/pull/53/files

**Comment by franzns** [comment]
hot fixed here https://github.com/balancer/backend/pull/76

still needs investigation why the poolId can be null.

**Comment by gmbronco** [comment]
All of the records with empty poolId are related to fbeets pool, where the poolID wasn't set. Fixed https://github.com/balancer/backend/pull/79
