### ISSUE TITLE
Staked balances not showing up

### ISSUE THREAD

**Issue by gmbronco** [balancer/backend#757]
It could have something to do with init actions. It can introduce data inconsistencies when we miss something. Resyncing with the subgraph should be a scheduled job.

**Comment by franzns** [comment]
Init is a super heavy query unfortunately, I wouldn't want to run that regularly

**Comment by gmbronco** [comment]
problem was solved by running init balances on the chain where they were missing. we might need to check if balances are properly initiated for new cow pools

**Comment by franzns** [comment]
oh, you did run the init mutation?

Hm, good point. We might want to check the logic for cow pools

**Comment by franzns** [comment]
fixed for cow
