### ISSUE TITLE
Support FX pools (apr, swap fee)

### ISSUE THREAD

**Issue by franzns** [balancer/backend#802]
Apparently FX pools have a dynamic swapfee. It seems we use a fixed one meaning that also the swap fee apr is off.

Info from Minteo

> About the pool fee:

The fee is dynamic based on the pool ratio, so its a bit complex, but maybe it is a good idea to display the epsilon from the pool contracts viewParameters (the minimum fee charged when the pool is within range which is charged most of the time) + a tooltip to explain this.

https://docs.xave.co/product-overview/fxpools/invariant-faqs

pool contract for reference: https://polygonscan.com/address/0xd4cc1afe3430c6c227f8f640d022bf5747538f53#readContract

> I am not sure about the apr, but that one is already visible in the old ui

https://app.balancer.fi/#/polygon/pool/0xd4cc1afe3430c6c227f8f640d022bf5747538f53000200000000000000000ebb

**Comment by andreiashu** [comment]
hi @franzns Xave team member here.
Yes, epsilon is the "static fee" parameter. That is a percentage value of the swap amount charged within a specific range (based on beta param) called the BETA range. If a swap is trying to take the pool outside that range, an added fee is charged which we call Dynamic Fee.

**Comment by gmbronco** [comment]
FX swap fees in the SG are negative when amountOut > amountIn resulting in negative cumulative snapshot values total swap fees on a pool.
