### ISSUE TITLE
Add cross chain veBal positions

### ISSUE THREAD

**Issue by gmbronco** [balancer/backend#805]
This is the FE implementation for tracking bridging events:

https://github.com/balancer/frontend-v2/blob/develop/src/providers/cross-chain-sync.provider.ts#L7

As far as i understand, end product is the list of vebal balances for the user.

<img width="1053" alt="image" src="https://github.com/user-attachments/assets/8a525740-2a13-4e15-bac9-fbf910dd78e1">

**Comment by franzns** [comment]
we already track veBal balance per user cross-chain. Each user has a veBal Balance per chain which is derived from what he has synced. This is needed to properly display the "my APR" in gauges with vebal boost.

**Comment by gmbronco** [comment]
Found it here: VeBalService.syncVeBalBalances, so we have it synced, and queryable but only for one chain, not all of them. Changing the query to multichain looks like a quick fix to this issue.

**Comment by gmbronco** [comment]
on top of the balances, FE would like to know if the balance is synced

**Comment by franzns** [comment]
> on top of the balances, FE would like to know if the balance is synced

Hm. I think they should rather do those onchain calls themselves.
