### ISSUE TITLE
AURA gauges

### ISSUE THREAD

**Issue by gmbronco** [balancer/backend#86]
We want to able to show aura gauges next to balancer gauges in the API. Things to consider:

* gauge addresses discoverability – ideally straight from on chain - so we don't need subgraph to rely on
* gauge rewards – check how similar it is to what we have in balancer
* gauge boost for bal – how to get it

Sync with Aura team to see how they are doing and if they would be interested in sharing what they have and perhaps contribute to the API.

**Comment by franzns** [comment]
It should also show APR as well as any user balances that are staked in the aura gauge

**Comment by franzns** [comment]
also add aura stakers to holders
