### ISSUE TITLE
sdBal > WETH swaps show no liquidity

### ISSUE THREAD

**Issue by johngrantuk** [balancer/backend#893]
Swaps from sdBal > WETH should have a path via new 80-20/WETH pool but no route showing.
(Should be sdBal[8020/sdBal-Pool]80-20[80-20/WETH]WETH)

Seems like there's a related issue as we also find no swap path for sdBal > 80-20 so this would be first part to investigate:https://balancer.fi/swap/ethereum/0xf24d8651578a55b0c119b9910759a351a3458895/B-80BAL-20WETH/1
- Are we filtering out this pool incorrectly somewhere?

- 80-20/WETH: https://balancer.fi/pools/ethereum/v2/0xc5c91aea7551095c3e1ff0f94f682c45b347ad730002000000000000000006c0
- 80-20/sdBal: https://balancer.fi/pools/ethereum/v2/0x2d011adf89f0576c9b722c28269fcb5d50c2d17900020000000000000000024d

**Comment by franzns** [comment]
Needs custom integration in the SDK similar to auraBAL

**Comment by johngrantuk** [comment]
> Needs custom integration in the SDK similar to auraBAL

Not neccesarily. There's a new weth/8020BPT pool that should open up swaps with longer paths too. This should start working once the issue is found for the sdBal<>8020BPT swap failing.
