### ISSUE TITLE
Review which error types don't need to be sent to Sentry

### ISSUE THREAD

**Issue by gmbronco** [balancer/backend#905]
Candidates for ignoring:

* missing chain param
* pool id not found
* sor:
  * The contract function "queryBatchSwap" reverted with the following
  * Invalid path, swap amount exceeds maximum for pool
  * Division by zero

**Comment by franzns** [comment]
sor division by zero comes from inputing 0 as swap amount. I think we should do input verification rather than ignoring the error for this.
