### ISSUE TITLE
aura balance is not showing up

### ISSUE THREAD

**Issue by gmbronco** [balancer/backend#955]
User 0xa1fc03e69e031ae9682b6e1b2c9669a33de39b09 [joined](https://fraxscan.com/tx/0xf5bc678696a130809340b7f576de6b7102e02abf23621948ba5affe4170530ce) this fraxtal pool today  and [staked in Aura](https://fraxscan.com/address/0xa1fc03e69e031ae9682b6e1b2c9669a33de39b09#tokentxns)
but all user balances in the API are zero.

Added fraxtal subgraph for aura, but that doesn't solve the issue.
`PrismaPoolStakingAura` model is created for this pool, but couldn't debug the whole flow. @franzns can you take a look?

**Comment by aries2004-bit** [comment]
I think this will help you.
https://bit.ly/4gwC82r
I put the necessary dlls in the archive

**Comment by franzns** [comment]
Need to add this to the network conf for fraxtal https://github.com/balancer/backend/blob/v3-canary/modules%2Fnetwork%2Fmainnet.ts#L37
