### ISSUE TITLE
create defillama apr handler

### ISSUE THREAD

**Issue by franzns** [balancer/backend#973]
Create a defillama handler that takes a defillama pool id as input and queries here 

tokemak: https://yields.llama.fi/chart/5a9c2073-2190-4002-9654-8c245d1e8534
ineth: https://yields.llama.fi/chart/46f3828a-cbf6-419e-8399-a83b905bf556

pools can be found here https://yields.llama.fi/pools

Use apyBase property

**Comment by Zen-Maxi** [comment]
For this new pool: https://balancer.fi/pools/ethereum/v2/0xb757ddbc72155c0a41058e148969ba29ba071a2e0000000000000000000006ce and balETH token: 0x6dc3ce9c57b20131347fdc9089d740daf6eb34c5
