### ISSUE TITLE
poolGetAggregatorPools - new fields

### ISSUE THREAD

**Issue by johngrantuk** [balancer/backend#979]
Could we get the following fields added to the `poolGetAggregatorPools`:
* token scalingFactors (as an array with ordering matching tokens)
* hook name (if the pool has an associated hook)
* hook address (if the pool has an associated hook)
* Also need a way to filter certain pool/hooks that may not support swaps so hook config and PoolConfig would be super helpful.

**Comment by franzns** [comment]
also add `totalSupply` and `bptPrice` as alternatives to `totalShares` and `sharePrice` because they seem to be confusing

**Comment by franzns** [comment]
> Could we get the following fields added to the `poolGetAggregatorPools`:
> * Also need a way to filter certain pool/hooks that may not support swaps so hook config and PoolConfig would be super helpful.

Should we already filter these pools out in the response?

**Comment by johngrantuk** [comment]
> > Could we get the following fields added to the `poolGetAggregatorPools`:
> > 
> > * Also need a way to filter certain pool/hooks that may not support swaps so hook config and PoolConfig would be super helpful.
> 
> Should we already filter these pools out in the response?

I think it would be pretty useful to already filter out pools that have swaps paused.
For pools with hooks - as well as having the hook/pool config would it be possible to somehow make it possible to query with something like `where: { hasHook: false }`? That way its easy to start integrating pools that don't have the added complexity of hooks.

**Comment by franzns** [comment]
> I think it would be pretty useful to already filter out pools that have swaps paused. 

Alright, we can filter that.

>For pools with hooks - as well as having the hook/pool config would it be possible to somehow make it possible to query with something like `where: { hasHook: false }`? That way its easy to start integrating pools that don't have the added complexity of hooks.

We can add some sort of filter for hooks, that works.
What exactly do you need from the pool config? We already sync certain fields, can you tell me which ones you are missing?

**Comment by johngrantuk** [comment]
> > I think it would be pretty useful to already filter out pools that have swaps paused.
> 
> Alright, we can filter that.
> 
> > For pools with hooks - as well as having the hook/pool config would it be possible to somehow make it possible to query with something like `where: { hasHook: false }`? That way its easy to start integrating pools that don't have the added complexity of hooks.
> 
> We can add some sort of filter for hooks, that works. What exactly do you need from the pool config? We already sync certain fields, can you tell me which ones you are missing?

Thanks!

In pool config the following LiquidityManagement is most useful as it potentialy causes issues with add/remove paths:
```
struct LiquidityManagement {
    bool disableUnbalancedLiquidity;
    bool enableAddLiquidityCustom;
    bool enableRemoveLiquidityCustom;
}
```

**Comment by franzns** [comment]
Filters, hook data and liquidity management data is available now

Asked Fabio about scalingFactor support from subgraph as this is immutable

**Comment by franzns** [comment]
done #1080
