### ISSUE TITLE
poolsSyncAllPoolsFromSubgraph fails on multiple chains

### ISSUE THREAD

**Issue by franzns** [balancer/backend#98]
fails on avax prod and test with
```Invalid `prisma.prismaPoolToken.upsert()` invocation:

  Foreign key constraint failed on the field: `PrismaPoolToken_address_chain_fkey (index)````

**Comment by franzns** [comment]
same job fails on polygon PROD with 
```"message": "Query interpretation error. Error for binding '1': AssertionError(\"Expected a valid parent ID to be present for nested update to-one case.\")"```

**Comment by gmbronco** [comment]
solved in #101 #106
